{
 "title": "Corepool",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Core Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Farmers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_active_farmers" }
   ]
  },
  {
   "title": "Pool Plots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_farmer_plots" }
   ]
  },
  {
   "title": "Pool Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_total_pool_size_pib" }
   ]
  },
  {
   "title": "Block Found",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_blocks_found", "legendFormat": "Today" },
    {
     "expr": "(corepool_blocks_found offset 1d)",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "My Plots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_total_plots" }
   ]
  },
  {
   "title": "Point Share",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_plot_points_percent" }
   ]
  },
  {
   "title": "Credit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_unpaid_balance", "legendFormat": "Unpaid" },
    {
     "expr": "corepool_unpaid_balance - (corepool_unpaid_balance offset 1d)",
     "legendFormat": "Reward Yesterday"
    }
   ]
  },
  {
   "title": "Farmer Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_farmer_status", "legendFormat": "{{farmer}}" }
   ]
  },
  {
   "title": "Plot Points",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corepool_plot_points" }
   ]
  },
  {
   "title": "Hourly Plot Points Increament",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(corepool_plot_points[1h])",
     "legendFormat": "Plot Points"
    }
   ]
  },
  {
   "title": "Daily Max Plot Points",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max_over_time(corepool_plot_points[1d])",
     "legendFormat": "Plot Points"
    }
   ]
  },
  {
   "title": "Daily Max Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max_over_time(corepool_blocks_found[1d])",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Daily Max Share Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max_over_time(corepool_plot_points_percent[1d])",
     "legendFormat": "Share"
    }
   ]
  }
 ]
}